#!/usr/bin/env bash

set -x
# echo "${@}"

config_dir=""

if [[ -n "${SVN_CONFIG_DIR}" ]]
then
    config_dir=--config-dir="${SVN_CONFIG_DIR}"
fi

is_under_version_control(){
    if [[ -n "${config_dir}" ]]
    then
        svn "${config_dir}" ls "${@}" >/dev/null 2>&1 \
            && return 0 || return 1
    fi
    svn ls "${@}" >/dev/null 2>&1
}

get_extension(){
    extension_revision="${1##*.}"
    extension_only="${extension_revision%%	*}"
    echo "${extension_only}"
}

path_left="${@: -5:1}"
path_right="${@: -3:1}"

if [[ "${path_left}" == *"(nonexistent)"* || "${path_right}" == *"(nonexistent)"* ]]
then
    echo "One of the paths is nonexistent. Skipping." 1>&2
    exit 1
fi

extension_left=`get_extension "${path_left}"`
extension_right=`get_extension "${path_right}"`

diff_arguments_size="$((${#} - 6))"
diff_arguments="${@:1:${diff_arguments_size}}"

diffopt=""

if [[ "${diff_arguments}" == "-w" || \
      "${diff_arguments}" == "-u" && \
      "${extension_left}" == "java" && "${extension_right}" == "java" ]]
then
    printf '\nIgnoring whitespace.\n'
    diffopt="set diffopt+=iwhite |"
fi

vim=/usr/bin/vim

if [[ "${EDITOR}" == *"vim" ]]
then
    vim="${EDITOR}"
fi

printf '\nDiff arguments are: "%s".\n' "${diff_arguments}"
printf '%s\n%s\n' "${path_left}" "${path_right}"
printf 'Editor is: "%s".\n\n' "${vim}"

file_left="${@: -2:1}"
file_right="${@: -1}"

make_temp_copy(){
    name="${1##*/}"
    name_no_tabs="${name//	/ }"
    temp_file="$(mktemp -d)/${name_no_tabs}"
    cp -f "${2}" "${temp_file}"
    echo "${temp_file}"
}

if ! is_under_version_control "${file_left}"
then
    file_left="$(make_temp_copy "${path_left}" "${file_left}")"
fi

if ! is_under_version_control "${file_right}"
then
    file_right="$(make_temp_copy "${path_right}" "${file_right}")"
fi

"${vim}" -d "${file_left}" "${file_right}"\
    -c "${diffopt}"'silent! set syntax='"${extension_left}"' | wincmd w '\
'| silent! set syntax='"${extension_right}"
