#!/usr/bin/env bash

# svn merge tool

# set -e

print_usage() {
	printf '\n%s\n' "$(basename $0) OLD HIS MINE MERGED WCPATH"
}

if [[ ! ${#} -eq 5 ]]
then
	print_usage 1>&2
	exit 1
fi

get_extension(){
    extension_revision="${1##*.}"
    extension_only="${extension_revision%%  *}"
    echo "${extension_only}"
}

old=${1}
his=${2}
mine=${3}
merged=${4}
wcpath=${5}

diff_program=diff

extension=`get_extension "${merged}"`

if [[ "${extension}" = "java" ]]
then
    printf '\nJava file. Ignoring whitespace.\n\n'
    diff_program=diffw
fi

diff3 --diff-program=${diff_program} -E -m "${mine}" "${old}" "${his}" \
    > "${merged}"

# querying for a CARRIAGE RETURN
if grep -q $'\x0d' "${merged}"
then
    if ! hash unix2dos
    then
        printf 'File contains carriage returns: unix2dos required.\n' 1>&2
        exit 1
    fi

    unix2dos -f "${merged}"
fi

vim=/usr/bin/vim

if [[ "${EDITOR}" != "${EDITOR%%vim}" ]]
then
    vim="${EDITOR}"
    printf '\nEditor is: "%s".\n' "${vim}"
fi

${vim} -d "${his}" "${old}" "${mine}" \
    -c "set ft=${extension} | setlocal nomodifiable" \
    -c "wincmd w | set ft=${extension} | setlocal nomodifiable" \
    -c "exec 'split '.fnameescape('""${merged}""') | wincmd J"\
    -c "silent set scrollbind cursorbind modifiable"
