#!/bin/bash

# svn merge tool

# set -e

print_usage() {
	printf '\n%s\n' "$(basename $0) OLD HIS MINE MERGED WCPATH"
}

if [ ! ${#} -eq 5 ]
then
	print_usage 1>&2
	exit 1
fi

get_extension(){
    echo "${1}" | sed 's/.*\.\([^.]\+\)\(\.merge.*\|\.working.*\|$\)/\1/'
}

vim=/usr/bin/nvim

if [ -n "${EDITOR}" ]
then
    vim="${EDITOR}"
fi

old=${1}
his=${2}
mine=${3}
merged=${4}
wcpath=${5}

diff_program=diff

extension=`get_extension "${merged}"`

if [ "${extension}" = "java" ]
then
    printf '\nJava file. Ignoring whitespace.\n\n'
    diff_program=diffw
fi

diff3 --diff-program=${diff_program} -E -m "${mine}" "${old}" "${his}" \
    > "${merged}"

# querying for a CARRIAGE RETURN
if grep -q $'\x0d' "${merged}"
then
    unix2dos -f "${merged}"
fi

${vim} -R -d "${his}" "${mine}" -c "set ft=${extension} | set nomodifiable" \
    -c "wincmd w | set ft=${extension} | set nomodifiable" \
    -c "split ""${merged}"" | wincmd J | silent set scrollbind cursorbind modifiable"
